### ISSUE TITLE
use case question : remote servers

### ISSUE THREAD

**Issue by joeblew99** [danderson/pixiecore#11]
i have servers located off site, where i have no control over the network config.
so they are behind a router, on a dynamic WAN IP etc.

I do get access to the servers BEFORE they are shipped off site and could put my software on them.
Like ubuntu core 15.4

Would this allow me to upgrade them using pixiecore ?
Sorry for dumb questions, maybe, i have never used PXE

As a side note. The other way i am looking at using using ubuntu core snap.
It allows transaction A / B parition based upgrades, like a chromebook, and i think coreos does.

**Comment by danderson** [comment]
Pixiecore is designed to either run on the same LAN segment as the target machine, or to be run in an environment where you control the switches/routers (so that you can specify a DHCP relay address).

If you don't control the machine's network, your options for remote REinstallation are pretty limited. The best I can think of right now would be to install iPXE with a static configuration that tells it to try and fetch a boot config over HTTPS. That way you could at least catch the machine attempting to boot - but pixiecore won't help you much with any of that, you'd need a custom solution for your deployment.

Personally, in that situation, I would probably go with CoreOS or some other A/B partition system, and either hope that the low-level booting never breaks, or buy and install a remote KVM device alongside the machines, so you always have remote "local-like" access. Such access, combined with iPXE installed in the NIC's PXE firmware, would get you the ability to make it netboot to an arbitrary HTTPS address and supervise installation progress.
