### ISSUE TITLE
Add support for a standalone mode that does not require a main DHCP server

### ISSUE THREAD

**Issue by rgl** [danderson/pixiecore#32]
It would be really nice to not require a main DHCP server at all. That is, use pixiecore to also provision the IPs et all. The library at https://github.com/krolaw/dhcp4/ might be useful for this.

**Comment by danderson** [comment]
This is something I've considered, but I'm concerned about implementing DHCP support directly, because that would miss out on a lot of battle-tested implementation tweaks that ISC dhcpd and dnsmasq have to deal with buggy clients.

That said, I've had this request through several different channels now, so it's time to bite the bullet and decide how to make it work.

**Comment by danderson** [comment]
Migrating Pixiecore to a new repository (I know, annoying), I've reflected this issue there: https://github.com/google/netboot/issues/3
