### ISSUE TITLE
Add IPFS (authenticated) File Fetch Support

### ISSUE THREAD

**Issue by JimDennis** [danderson/pixiecore#34]
Perhaps added to the PXELinux code, it would be nice to add support for IPFS (https://ipfs.io/) as an alternative to HTTP/FTP for fetching menu pages, splash images, kernels, initramfs and any other data to be displayed or executed.

IPFS identifiers (path/filenames) contain the content authentication data (SHA-256) which can thus narrow the exposure to MITM (man-in-the-middle) attacks on newly booting hosts.  (The firmware's TFTP of the _pixielinux.0_ (_lpixielinux.0_ in the pixiecore source tree) file is still vulnerable ... but the rest of the files (normally fetched via HTTP or FTP) and often from a more central server across a routed network) would be more secure.

Unfortunately it doesn't appear that there's an implementation of _libp2p_ in C yet (https://github.com/ipfs/ipfs/blob/master/ROADMAP.md) and so that might be a bit of the work for this.

Potentially helpful reading:

-  http://www.0xf8.org/2012/04/clarifying-the-relationship-between-pxelinux-etherboot-and-gpxeipxe
- https://github.com/zignig/astralboot
- http://ipxe.org/
- https://github.com/ipfs/ipget

**Comment by arnehormann** [comment]
Disclaimer: I'm not a dev, just a user and one time PR author.

Pixiecore only covers the server side. It sends a payload to the client which loads the kernel and initrd. That payload is just a binary from an external source and not a maintained part of pixiecore.

Unless you want the server to download from IPFS and serve via http (wouldn't buy you much IMO and is already possible in a user supplied [apiserver](https://github.com/danderson/pixiecore/blob/master/example/main.go)), IPFS support would have to land in that binary - pxelinux or ipxe.
Supplying a url which references an IPFS resource should already be possible if it's just a string.

This issue should be solved by incorporating a new pxelinux or ipxe version as soon IPFS support has landed there.
In pixiecore, it's pxelinux. Its next version in github.com/google/netboot uses ipxe (unstable and in development, do not use in production).

I think this issue is best resolved by adding IPFS support in ipxe, so you'd best post an issue [there](http://ipxe.org/contact).

**Comment by JimDennis** [comment]
On Sun, Aug 14, 2016 at 4:08 AM, Arne Hormann <notifications@github.com>
wrote:

> Disclaimer: I'm not a dev, just a user and one time PR author.
>
> Pixiecore only covers the server side. It sends a payload to the client
> which loads the kernel and initrd. That payload is just a binary from an
> external source and not a maintained part of pixiecore.
>

Actually what I'd like is for Pixiecore's version of `pxelinux.0` (or for
the H. Peter Anvin or the current maintainers of SysLinux/PXElinux) to
add/support the SHA-256 (and any other IPFS supported authentication
hashes).

This would allow the existing HTTP fetching code to be used; but still
integrate content authentication into the content's address.

Unless you want the server to download from IPFS and serve via http
> (wouldn't buy you much IMO and is already possible in a user supplied
> apiserver
> <https://github.com/danderson/pixiecore/blob/master/example/main.go>),
> IPFS support would have to land in that binary - pxelinux or ipxe.
>
Yes; I agree that the new code/support needs to be in `pxelinux.0` or iPXE
(if `pixiecore` support iPXE).

 In my opinion you still get plenty by supporting the content
authentication even wrapped around HTTP fetch.This seems much simpler, more
robust and more scalable than SSL, HSTS and related technologies --- and
only costs a bit of SHA-* checking code and imposes constraint on the HTTP
URL (encoding the MAC/hash into the path and requiring that the HTTP server
support such paths --- though that is mostly done via static directory
naming and would be completely transparent to common web site mirroring
strategies).


> Supplying a url which references an IPFS resource should already be
> possible if it's just a string.
>
> This issue should be solved by incorporating a new pxelinux or ipxe
> version as soon IPFS support has landed there.
>


> In pixiecore, it's pxelinux. Its next version in github.com/google/netboot
> uses ipxe (unstable and in development, do not use in production).
>
 I see how iPXE is slated for the future roadmap.  Thanks.

I think this issue is best resolved by adding IPFS support in ipxe, so
> you'd best post an issue there <http://ipxe.org/contact>.
>
 Will do.

**Comment by danderson** [comment]
Closing this out since, as @arnehormann pointed out, I'd first need IPFS support to show up in ipxe before I can plumb it through Pixiecore.

(also closing because I'm officially kicking development over to the new repository now).
